// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Voting.ServiceContracts.DbContexts;

namespace Voting.Migrations.PgSqlMigrations
{
    [DbContext(typeof(VotingContextPgSql))]
    [Migration("20181224081924_RemovedExpiredElectionsFunctionPostgreSql")]
    partial class RemovedExpiredElectionsFunctionPostgreSql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Voting.ServiceContracts.Models.Ballot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ElectionId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.ToTable("Ballots");
                });

            modelBuilder.Entity("Voting.ServiceContracts.Models.BallotCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BallotId");

                    b.Property<int?>("CandidateId");

                    b.Property<int>("VoteCount");

                    b.HasKey("Id");

                    b.HasIndex("BallotId");

                    b.HasIndex("CandidateId");

                    b.ToTable("BallotCandidates");
                });

            modelBuilder.Entity("Voting.ServiceContracts.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Voting.ServiceContracts.Models.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<Guid>("ElectionQr");

                    b.Property<DateTime>("ExpirationDate");

                    b.HasKey("Id");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("Voting.ServiceContracts.Models.Ballot", b =>
                {
                    b.HasOne("Voting.ServiceContracts.Models.Election")
                        .WithMany("Ballots")
                        .HasForeignKey("ElectionId");
                });

            modelBuilder.Entity("Voting.ServiceContracts.Models.BallotCandidate", b =>
                {
                    b.HasOne("Voting.ServiceContracts.Models.Ballot", "Ballot")
                        .WithMany()
                        .HasForeignKey("BallotId");

                    b.HasOne("Voting.ServiceContracts.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId");
                });
#pragma warning restore 612, 618
        }
    }
}
